package com.wqp.grab.module.qxc.dao;

import com.wqp.grab.module.common.annotation.MyBatisDao;
import com.wqp.grab.module.qxc.entity.Dynamic;

@MyBatisDao
public interface DynamicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    int insert(Dynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    int insertSelective(Dynamic record);
}