package com.wqp.grab.module.qxc.dao;

import com.wqp.grab.module.common.annotation.MyBatisDao;
import com.wqp.grab.module.qxc.entity.QiXingCai;
import org.springframework.stereotype.Component;

import java.util.List;

@MyBatisDao
public interface QiXingCaiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qxc
     *
     * @mbg.generated
     */
    int insert(QiXingCai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qxc
     *
     * @mbg.generated
     */
    int insertSelective(QiXingCai record);

    List<QiXingCai> findAll();

    int statisticsByrFrequency(QiXingCai record);//统计
}