package com.wqp.grab.module.qxc.dao;

import com.wqp.grab.module.common.annotation.MyBatisDao;
import com.wqp.grab.module.qxc.entity.Recommend;

@MyBatisDao
public interface RecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    int insert(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    int insertSelective(Recommend record);
}