package com.wqp.grab.module.qxc.dao;

import com.wqp.grab.module.common.annotation.MyBatisDao;
import com.wqp.grab.module.qxc.entity.Statistics;
import org.springframework.stereotype.Component;

import java.util.List;

@MyBatisDao
public interface StatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Thu Oct 26 17:47:31 CST 2017
     */
    int insert(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Thu Oct 26 17:47:31 CST 2017
     */
    int insertSelective(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Thu Oct 26 17:47:31 CST 2017
     */
    List<Statistics> findByExpress(Statistics record);
}