package com.wqp.grab.module.qxc.dao;

import com.wqp.grab.module.common.annotation.MyBatisDao;
import com.wqp.grab.module.qxc.entity.WinHistory;

import java.util.List;

@MyBatisDao
public interface WinHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_history
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    int insert(WinHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_history
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    int insertSelective(WinHistory record);

    List<WinHistory> findByExpress(WinHistory record);
}