package com.wqp.grab.module.qxc.entity;

/**
 * 预测号码动态更新类
 */
public class Dynamic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.ID
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.ISSUE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private Integer issue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.WIN_NUMBER
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String winNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.CLASSIFY
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String classify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.ORIGIN
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String origin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.ZERO
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String zero;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.ONE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String one;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.TWO
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String two;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.THREE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String three;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.FOUR
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String four;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.FIVE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String five;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.SIX
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String six;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.SEVEN
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String seven;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.EIGHT
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String eight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.NINE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String nine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.NINE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private Integer frequencyValidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.NINE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private Integer radix;

    public Integer getFrequencyValidity() {
        return frequencyValidity;
    }

    public void setFrequencyValidity(Integer frequencyValidity) {
        this.frequencyValidity = frequencyValidity;
    }

    public Integer getRadix() {
        return radix;
    }

    public void setRadix(Integer radix) {
        this.radix = radix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.ID
     *
     * @return the value of dynamic.ID
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.ID
     *
     * @param id the value for dynamic.ID
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.ISSUE
     *
     * @return the value of dynamic.ISSUE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public Integer getIssue() {
        return issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.ISSUE
     *
     * @param issue the value for dynamic.ISSUE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setIssue(Integer issue) {
        this.issue = issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.WIN_NUMBER
     *
     * @return the value of dynamic.WIN_NUMBER
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getWinNumber() {
        return winNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.WIN_NUMBER
     *
     * @param winNumber the value for dynamic.WIN_NUMBER
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setWinNumber(String winNumber) {
        this.winNumber = winNumber == null ? null : winNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.CLASSIFY
     *
     * @return the value of dynamic.CLASSIFY
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.CLASSIFY
     *
     * @param classify the value for dynamic.CLASSIFY
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setClassify(String classify) {
        this.classify = classify == null ? null : classify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.ORIGIN
     *
     * @return the value of dynamic.ORIGIN
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.ORIGIN
     *
     * @param origin the value for dynamic.ORIGIN
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.ZERO
     *
     * @return the value of dynamic.ZERO
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getZero() {
        return zero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.ZERO
     *
     * @param zero the value for dynamic.ZERO
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setZero(String zero) {
        this.zero = zero == null ? null : zero.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.ONE
     *
     * @return the value of dynamic.ONE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getOne() {
        return one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.ONE
     *
     * @param one the value for dynamic.ONE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setOne(String one) {
        this.one = one == null ? null : one.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.TWO
     *
     * @return the value of dynamic.TWO
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getTwo() {
        return two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.TWO
     *
     * @param two the value for dynamic.TWO
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setTwo(String two) {
        this.two = two == null ? null : two.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.THREE
     *
     * @return the value of dynamic.THREE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getThree() {
        return three;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.THREE
     *
     * @param three the value for dynamic.THREE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setThree(String three) {
        this.three = three == null ? null : three.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.FOUR
     *
     * @return the value of dynamic.FOUR
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getFour() {
        return four;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.FOUR
     *
     * @param four the value for dynamic.FOUR
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setFour(String four) {
        this.four = four == null ? null : four.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.FIVE
     *
     * @return the value of dynamic.FIVE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getFive() {
        return five;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.FIVE
     *
     * @param five the value for dynamic.FIVE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setFive(String five) {
        this.five = five == null ? null : five.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.SIX
     *
     * @return the value of dynamic.SIX
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getSix() {
        return six;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.SIX
     *
     * @param six the value for dynamic.SIX
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setSix(String six) {
        this.six = six == null ? null : six.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.SEVEN
     *
     * @return the value of dynamic.SEVEN
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getSeven() {
        return seven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.SEVEN
     *
     * @param seven the value for dynamic.SEVEN
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setSeven(String seven) {
        this.seven = seven == null ? null : seven.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.EIGHT
     *
     * @return the value of dynamic.EIGHT
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getEight() {
        return eight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.EIGHT
     *
     * @param eight the value for dynamic.EIGHT
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setEight(String eight) {
        this.eight = eight == null ? null : eight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.NINE
     *
     * @return the value of dynamic.NINE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getNine() {
        return nine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.NINE
     *
     * @param nine the value for dynamic.NINE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setNine(String nine) {
        this.nine = nine == null ? null : nine.trim();
    }
}