package com.wqp.grab.module.qxc.entity;

import java.util.Date;

/**
 * 往期中奖号码类
 */
public class QiXingCai {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.ISSUE
     *
     * @mbg.generated
     */
    private Integer issue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.WIN_NUMBER
     *
     * @mbg.generated
     */
    private String winNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qxc.ID
     *
     * @return the value of qxc.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qxc.ID
     *
     * @param id the value for qxc.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qxc.ISSUE
     *
     * @return the value of qxc.ISSUE
     *
     * @mbg.generated
     */
    public Integer getIssue() {
        return issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qxc.ISSUE
     *
     * @param issue the value for qxc.ISSUE
     *
     * @mbg.generated
     */
    public void setIssue(Integer issue) {
        this.issue = issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qxc.WIN_NUMBER
     *
     * @return the value of qxc.WIN_NUMBER
     *
     * @mbg.generated
     */
    public String getWinNumber() {
        return winNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qxc.WIN_NUMBER
     *
     * @param winNumber the value for qxc.WIN_NUMBER
     *
     * @mbg.generated
     */
    public void setWinNumber(String winNumber) {
        this.winNumber = winNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qxc.CREATE_TIME
     *
     * @return the value of qxc.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qxc.CREATE_TIME
     *
     * @param createTime the value for qxc.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public QiXingCai(String winNumber) {
        this.winNumber = winNumber;
    }

    public QiXingCai() {
    }
}