package com.wqp.grab.module.qxc.entity;

/**
 * 预测号码推荐类
 */
public class Recommend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.ID
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.ISSUE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private Integer issue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.FORECAST
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    private String forecast;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.ID
     *
     * @return the value of recommend.ID
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.ID
     *
     * @param id the value for recommend.ID
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.ISSUE
     *
     * @return the value of recommend.ISSUE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public Integer getIssue() {
        return issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.ISSUE
     *
     * @param issue the value for recommend.ISSUE
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setIssue(Integer issue) {
        this.issue = issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.FORECAST
     *
     * @return the value of recommend.FORECAST
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public String getForecast() {
        return forecast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.FORECAST
     *
     * @param forecast the value for recommend.FORECAST
     *
     * @mbg.generated Fri Oct 27 00:16:12 CST 2017
     */
    public void setForecast(String forecast) {
        this.forecast = forecast == null ? null : forecast.trim();
    }

    public Recommend(Integer issue, String forecast) {
        this.issue = issue;
        this.forecast = forecast;
    }
}