package com.wqp.grab.module.qxc.entity;

/**
 * 往期中奖号码统计类
 */
public class Statistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.ISSUE
     *
     * @mbg.generated
     */
    private Integer issue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.WIN_NUMBER
     *
     * @mbg.generated
     */
    private String winNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.ISSUE
     *
     * @mbg.generated
     */
    private Integer frequency;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.WIN_NUMBER
     *
     * @mbg.generated
     */
    private String batch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.WIN_NUMBER
     *
     * @mbg.generated
     */
    private String aboveFour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.WIN_NUMBER
     *
     * @mbg.generated
     */
    private String aboveFourSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.WIN_NUMBER
     *
     * @mbg.generated
     */
    private String geWei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.WIN_NUMBER
     *
     * @mbg.generated
     */
    private String shiWei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.WIN_NUMBER
     *
     * @mbg.generated
     */
    private String baiWei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qxc.WIN_NUMBER
     *
     * @mbg.generated
     */
    private String qianWei;

    public String getAboveFour() {
        return aboveFour;
    }

    public void setAboveFour(String aboveFour) {
        this.aboveFour = aboveFour;
    }

    public String getAboveFourSum() {
        return aboveFourSum;
    }

    public void setAboveFourSum(String aboveFourSum) {
        this.aboveFourSum = aboveFourSum;
    }

    public String getGeWei() {
        return geWei;
    }

    public void setGeWei(String geWei) {
        this.geWei = geWei;
    }

    public String getShiWei() {
        return shiWei;
    }

    public void setShiWei(String shiWei) {
        this.shiWei = shiWei;
    }

    public String getBaiWei() {
        return baiWei;
    }

    public void setBaiWei(String baiWei) {
        this.baiWei = baiWei;
    }

    public String getQianWei() {
        return qianWei;
    }

    public void setQianWei(String qianWei) {
        this.qianWei = qianWei;
    }

    public String getBatch() {
        return batch;
    }

    public void setBatch(String batch) {
        this.batch = batch;
    }

    public Integer getFrequency() {
        return frequency;
    }

    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIssue() {
        return issue;
    }

    public void setIssue(Integer issue) {
        this.issue = issue;
    }

    public String getWinNumber() {
        return winNumber;
    }

    public void setWinNumber(String winNumber) {
        this.winNumber = winNumber;
    }

    public Statistics() {
    }

    public Statistics(String batch) {
        this.batch = batch;
    }
}