package com.wqp.grab.module.qxc.entity;

public class WinHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_history.ISSUE
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    private String issue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_history.WIN_NUMBER
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    private String winNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_history.FRONT_NUMBER
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    private String frontNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_history.QIAN
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    private String qian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_history.BAI
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    private String bai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_history.SHI
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    private String shi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column win_history.GE
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    private String ge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_history.ISSUE
     *
     * @return the value of win_history.ISSUE
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public String getIssue() {
        return issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_history.ISSUE
     *
     * @param issue the value for win_history.ISSUE
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public void setIssue(String issue) {
        this.issue = issue == null ? null : issue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_history.WIN_NUMBER
     *
     * @return the value of win_history.WIN_NUMBER
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public String getWinNumber() {
        return winNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_history.WIN_NUMBER
     *
     * @param winNumber the value for win_history.WIN_NUMBER
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public void setWinNumber(String winNumber) {
        this.winNumber = winNumber == null ? null : winNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_history.FRONT_NUMBER
     *
     * @return the value of win_history.FRONT_NUMBER
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public String getFrontNumber() {
        return frontNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_history.FRONT_NUMBER
     *
     * @param frontNumber the value for win_history.FRONT_NUMBER
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public void setFrontNumber(String frontNumber) {
        this.frontNumber = frontNumber == null ? null : frontNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_history.QIAN
     *
     * @return the value of win_history.QIAN
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public String getQian() {
        return qian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_history.QIAN
     *
     * @param qian the value for win_history.QIAN
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public void setQian(String qian) {
        this.qian = qian == null ? null : qian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_history.BAI
     *
     * @return the value of win_history.BAI
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public String getBai() {
        return bai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_history.BAI
     *
     * @param bai the value for win_history.BAI
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public void setBai(String bai) {
        this.bai = bai == null ? null : bai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_history.SHI
     *
     * @return the value of win_history.SHI
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public String getShi() {
        return shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_history.SHI
     *
     * @param shi the value for win_history.SHI
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public void setShi(String shi) {
        this.shi = shi == null ? null : shi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column win_history.GE
     *
     * @return the value of win_history.GE
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public String getGe() {
        return ge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column win_history.GE
     *
     * @param ge the value for win_history.GE
     *
     * @mbg.generated Wed Nov 22 21:58:19 CST 2017
     */
    public void setGe(String ge) {
        this.ge = ge == null ? null : ge.trim();
    }
}