package com.wqp.grab.module.emr.entity;

public class HisEmrAdjunct<T> {
    /**
     * 附件
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    private String adjunctId;

    /**
     * 电子病历
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    private String emrId;

    /**
     * 附件类别,1:检查申请单;2:化验申请单;3:治疗单;4:处方单;5:影像资料
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    private Integer category;

    /**
     * 附件,其中检查申请单、化验申请单、治疗单、处方单存放编号ID；影像资料存放文件路径
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    private String adjunct;

    /**
     * 附件有效性;1:有效;2:无效
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    private Integer validity;

    /**
     * 附件数据
     */
    private T t;


    public T getT() {
        return t;
    }

    public void setT(T t) {
        this.t = t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_emr_adjunct.ADJUNCT_ID
     *
     * @return the value of his_emr_adjunct.ADJUNCT_ID
     *
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    public String getAdjunctId() {
        return adjunctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_emr_adjunct.ADJUNCT_ID
     *
     * @param adjunctId the value for his_emr_adjunct.ADJUNCT_ID
     *
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    public void setAdjunctId(String adjunctId) {
        this.adjunctId = adjunctId == null ? null : adjunctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_emr_adjunct.EMR_ID
     *
     * @return the value of his_emr_adjunct.EMR_ID
     *
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    public String getEmrId() {
        return emrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_emr_adjunct.EMR_ID
     *
     * @param emrId the value for his_emr_adjunct.EMR_ID
     *
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    public void setEmrId(String emrId) {
        this.emrId = emrId == null ? null : emrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_emr_adjunct.CATEGORY
     *
     * @return the value of his_emr_adjunct.CATEGORY
     *
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_emr_adjunct.CATEGORY
     *
     * @param category the value for his_emr_adjunct.CATEGORY
     *
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_emr_adjunct.ADJUNCT
     *
     * @return the value of his_emr_adjunct.ADJUNCT
     *
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    public String getAdjunct() {
        return adjunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_emr_adjunct.ADJUNCT
     *
     * @param adjunct the value for his_emr_adjunct.ADJUNCT
     *
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    public void setAdjunct(String adjunct) {
        this.adjunct = adjunct == null ? null : adjunct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_emr_adjunct.VALIDITY
     *
     * @return the value of his_emr_adjunct.VALIDITY
     *
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    public Integer getValidity() {
        return validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_emr_adjunct.VALIDITY
     *
     * @param validity the value for his_emr_adjunct.VALIDITY
     *
     * @mbg.generated Wed Dec 13 10:25:53 CST 2017
     */
    public void setValidity(Integer validity) {
        this.validity = validity;
    }
}